# Generated by Django 2.2 on 2019-04-13 14:11

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('last_ip', models.GenericIPAddressField()),
                ('resolver_cache', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
